package org.mejdi14.project.helpers

const val SWITCHER_ANIMATION_DURATION = 800L
const val COLOR_ANIMATION_DURATION = 300L
const val BOUNCE_ANIM_AMPLITUDE_IN = 0.2
const val BOUNCE_ANIM_AMPLITUDE_OUT = 0.1
const val BOUNCE_ANIM_FREQUENCY_IN = 14.5
const val ANIMATION_SPEED_EXIT = 8.0
const val CURSOR_BLINK_DURATION = 900
const val TYPING_THRESHOLD_MS = 500
const val ICON_RADIUS_FACTOR = 0.5f
const val ICON_CLIP_RADIUS_FACTOR = 0.5f
const val ICON_COLLAPSED_WIDTH_SCALE = 1.1f
const val TRANSLATION_Y_CHECKED_FACTOR = 0.06f

const val LINE_START_X_FACTOR = 0.5f
const val LINE_END_X_FACTOR = 0.5f
const val ELEVATION_LINE_FACTOR = 0.5f
const val SWITCH_RADIUS_LINE_FACTOR = 0.7f
const val LINE_SQUEEZE_BOUNCE_FACTOR = 0.2f

const val RECT_CORNER_FACTOR = 1.0f