name: Build Release
on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  env-vars:
    name: Generate Env Vars
    runs-on: ubuntu-latest
    outputs:
      stamp-version-pretty: ${{ steps.stamp-version-pretty.outputs.stamp }}
      stamp-version-name: ${{ steps.stamp-version-name.outputs.stamp }}
      stamp-version-code: ${{ steps.stamp-version-code.outputs.stamp }}
    steps:
      - uses: actions/checkout@v2

      - name: Export Release Timestamp
        id: stamp-version-pretty
        run: echo "::set-output name=stamp::v$(date +'%y.%m.%d-%H%M')"

      - name: Generate Build Name
        id: stamp-version-name
        run: echo "::set-output name=stamp::$(date +'%y.%m.%d')"

      - name: Generate Build Number
        id: stamp-version-code
        run: echo "::set-output name=stamp::$(( ($(date +%s) - $(date +%s -d '2022-01-01 00:00:00')) / 60 / 5))"

  build:
    name: Build, Analyze & Document
    runs-on: ubuntu-latest
    needs: env-vars
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      # Run Detekt for static code analysis
      - name: Run Detekt
        run: ./gradlew detekt --stacktrace

      # Generate documentation using Dokka
      - name: Generate Dokka Documentation
        run: ./gradlew dokkaHtml --stacktrace

      # Build the project
      - name: Build Project
        run: ./gradlew build --stacktrace

  release:
    name: Release Artifacts
    runs-on: ubuntu-latest
    needs: [build, env-vars]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Optionally upload generated Dokka documentation as an artifact
      - name: Upload Dokka Docs
        uses: actions/upload-artifact@v2
        with:
          name: dokka-docs
          path: build/dokka

      # Create a release using the generated env vars and artifacts
      - name: Create Release
        uses: ncipollo/release-action@v1.9.0
        with:
          name: ${{ needs.env-vars.outputs.stamp-version-name }}+${{ needs.env-vars.outputs.stamp-version-code }}
          tag: ${{ needs.env-vars.outputs.stamp-version-pretty }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: build/dokka/**
